# action.yml
name: 'Gitlog Analyzer'
description: 'Executes an analysis of a git log file to determine coupling and commit frequencies, defaults to last month of commits.'
inputs:
  init date:
    description: 'Starting date to analyze git log from, format is: yyyy-mm-dd'
    required: false
  min cochanges:
    description: 'Minimum number of cochanges to report in coupling analysis'
    required: false
    default: '0'
outputs:
  frecuencies:
    description: 'The result of commit frequencies analysis'
  coupling:
    description: 'The result of the coupling analysis'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: "code"
    color: "black"
